# .travis.yml
dist: precise

language: php

php:
  - 7.3
  - 8.0

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests
